apiVerions: kubeam.io/v1beta1
kind: InitConfiguration
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeamd:default-node-token
  token: abcdef.01234678abcdef
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
localAPIEndpoint:
  advertiseAddress: x.x.x.x
  bindPort: 6443
nodeRegistration:
  kubeletExtraArgs:
    cloud-provider: aws
  criSocket: /var/run/dockershim.sock
  name: ip-x-x-x-x.ec2.internal
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: v1.13.4
imageRepository: k8s.gcr.io
apiServer:
  timeoutForcontrolPlane: 4m0s
  extraArgs:
    cloud-provider: aws
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controlPlaneEndpoint: ""
controllerManager:
  extraArgs:
    cloud-provider: aws
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
networking:
  dnsDomain: cluster.local
  podSubnet: ""
  serviceSubnet: x.x.x.x/12
scheduler: {}
