kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pipe2
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      type: local
